language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  - EXTRA_REMOTES="https://github.com/djs55/opam-repository.git#io-page"
  matrix:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
