.PHONY: build

build:
	cd core && $(MAKE) build && $(MAKE) install

uninstall:
	cd core && $(MAKE) uninstall

build-bindings:
	cd bindings && $(MAKE) build && $(MAKE) install

uninstall-bindings:
	cd bindings && $(MAKE) uninstall
