#!/bin/sh -e
# Build a Mirage Xen binary from an OCaml native code

set -e

usage() {
  cat << EOF
Build a Mirage binary from the OCaml compiler output.

Usage: $0 [-h] [-o <file>] [-b <backend>] <object file>

BACKENDS:
  xen-native (default)
  
OPTIONS:
   -o     Output final binary to <file>.
   -b     Mirage backend to use (see BACKENDS above)
   -h     Show this usage message.
EOF
  exit 1
}

link_xen_native() {
  OBJ=$1
  OUTPUT=$2
  LIB=`ocamlfind query mirage`

  ld -d -nostdlib -m elf_x86_64 -T ${LIB}/mirage-x86_64.lds \
    ${LIB}/x86_64.o ${OBJ} ${LIB}/libocaml.a ${LIB}/libxen.a \
    ${LIB}/libxencaml.a ${LIB}/libdiet.a ${LIB}/libm.a ${LIB}/longjmp.o -o $2
}

link_ns3_native() {
  OBJ=$1
  OUTPUT=$2
  LIB=`ocamlfind query mirage`

  if [ -e "/usr/local/lib/libns3.16-core-optimized.dylib" ]; then
    NS3_LIB="-L/usr/local/lib/ -lns3.16-core-optimized -lns3.16-network-optimized -lns3.16-point-to-point-optimized -lns3.16-mpi-optimized "
  elif [ -e "/usr/lib/libns3.15-core.so" ]; then
    NS3_LIB="-L/usr/lib/ -lns3.15-core -lns3.15-network -lns3.15-point-to-point -lns3.15-tap-bridge -lns3.15-mpi"
  elif [ -e "/usr/lib/libns3-core.so" ]; then
    NS3_LIB="-lns3-core -lns3-network -lns3-point-to-point -lns3-tap-bridge -lns3-mpi"
  else
    echo "cannot find libns3 in a known location. Please follow instruction to install ns3 libraries."
  fi

  echo "using $NS3_LIB flags for app building"
  case `uname` in 
    Darwin) 
    cc -arch x86_64 \
    -execute \
    -lc \
    ${LIB}/main_stubs.o \
    ${OBJ} \
    ${LIB}/libns3run.a \
    ${LIB}/../ocaml/libunix.a \
    ${LIB}/../ocaml/libasmrun.a \
    ${LIB}/../cstruct/libcstruct_stubs.a \
    ${LIB}/../ocaml/libbigarray.a \
    -lstdc++ \
    $NS3_LIB \
    ${LIB}/clock_stubs.o \
    ${LIB}/console_stubs.o \
    ${LIB}/checksum_stubs.o \
    ${LIB}/ns_stubs.o \
    -o ${OUTPUT}
    ;;
    Linux)
    g++ \
    ${OBJ} \
    ${LIB}/libns3run.a \
    ${LIB}/../ocaml/libunix.a \
    ${LIB}/../ocaml/libasmrun.a \
    ${LIB}/../cstruct/libcstruct_stubs.a \
    ${LIB}/../ocaml/libbigarray.a \
    -L/usr/lib/ \
    -lns3.15-core \
    -lns3.15-network \
    -lns3.15-point-to-point \
    -lns3.15-tap-bridge \
    -lns3.15-mpi \
    -o ${OUTPUT}
    ;;
  esac
}


BACKEND=xen-native
while [ $# -gt 0 ]; do
  case "$1" in
  -b)
    shift
    BACKEND=$1
    ;;
  -o)
    shift
    OUTPUT="$1"
    ;;
  -h)
    usage
    ;;
  *)
    OBJFILE="$1"
    ;;
  esac
  shift
done

if [ "${OBJFILE}" = "" ]; then
  usage
fi

case "$BACKEND" in
"xen-native")
  link_xen_native ${OBJFILE} ${OUTPUT}
  ;;
"ns3-native")
  link_ns3_native ${OBJFILE} ${OUTPUT}
  ;;
*)
  echo Unknown backend $BACKEND
  exit 1
  ;;
esac
